return function(colours)
	vim.api.nvim_set_hl(0, "GrugFarHelpHeader", { fg = colours.mauve, bold = true })
	vim.api.nvim_set_hl(0, "GrugFarHelpHeaderKey", { fg = colours.sapphire })
	vim.api.nvim_set_hl(0, "GrugFarInputLabel", { fg = colours.mauve, bold = true })
	vim.api.nvim_set_hl(0, "GrugFarInputPlaceholder", { fg = colours.overlay0, italic = true })
	vim.api.nvim_set_hl(0, "GrugFarResultsHeader", { fg = colours.mauve, bold = true })
	vim.api.nvim_set_hl(0, "GrugFarResultMatch", { fg = colours.bg, bg = colours.mauve })
	vim.api.nvim_set_hl(0, "GrugFarResultMatchAdded", { fg = colours.bg, bg = colours.green })
	vim.api.nvim_set_hl(0, "GrugFarResultMatchRemoved", { fg = colours.bg, bg = colours.red })
	vim.api.nvim_set_hl(0, "GrugFarResultLineNo", { fg = colours.overlay0 })
	vim.api.nvim_set_hl(0, "GrugFarResultsChangeIndicator", { fg = colours.yellow })
	vim.api.nvim_set_hl(0, "GrugFarResultsAddedIndicator", { fg = colours.green })
	vim.api.nvim_set_hl(0, "GrugFarResultsRemovedIndicator", { fg = colours.red })
	vim.api.nvim_set_hl(0, "GrugFarResultsStatsHeader", { fg = colours.subtext, italic = true })
	vim.api.nvim_set_hl(0, "GrugFarFilePath", { fg = colours.blue, bold = true })
	vim.api.nvim_set_hl(0, "GrugFarCount", { fg = colours.peach, bold = true })
	vim.api.nvim_set_hl(0, "GrugFarSearchProgress", { fg = colours.sapphire, italic = true })
end
