return function(colours)
	vim.api.nvim_set_hl(0, "@variable", { fg = colours.sapphire })
	vim.api.nvim_set_hl(0, "@Keyword", { fg = colours.mauve })
	vim.api.nvim_set_hl(0, "@constant", { fg = colours.mauve })
	vim.api.nvim_set_hl(0, "@lsp.type.enumMember", { fg = colours.sapphire })
	vim.api.nvim_set_hl(0, "@method.call", { fg = colours.blue })
	vim.api.nvim_set_hl(0, "@function", { fg = colours.sapphire })
	vim.api.nvim_set_hl(0, "@function.call", { fg = colours.sapphire })
	vim.api.nvim_set_hl(0, "@function.macro", { fg = colours.mauve })
	vim.api.nvim_set_hl(0, "@type", { fg = colours.green })
	vim.api.nvim_set_hl(0, "@type.builtin", { fg = colours.mauve })
	vim.api.nvim_set_hl(0, "@parameter", { fg = colours.subtext })
	vim.api.nvim_set_hl(0, "@attribute", { fg = colours.subtext })
	vim.api.nvim_set_hl(0, "@property", { fg = colours.blue })
	vim.api.nvim_set_hl(0, "@boolean", { fg = colours.yellow })
	vim.api.nvim_set_hl(0, "@operator", { fg = colours.blue })
	vim.api.nvim_set_hl(0, "@module", { fg = colours.yellow })
	vim.api.nvim_set_hl(0, "@include", { fg = colours.mauve })
	vim.api.nvim_set_hl(0, "@label", { fg = colours.red })
	vim.api.nvim_set_hl(0, "@character", { fg = colours.yellow })
	vim.api.nvim_set_hl(0, "@float", { fg = colours.sapphire })
	vim.api.nvim_set_hl(0, "@string.special", { fg = colours.red })
	vim.api.nvim_set_hl(0, "@punctuation.delimiter", { fg = colours.subtext })
	vim.api.nvim_set_hl(0, "@punctuation.bracket", { fg = colours.subtext })
	vim.api.nvim_set_hl(0, "@markup.heading", { fg = colours.mauve, bold = true })
	vim.api.nvim_set_hl(0, "@markup.strong", { fg = colours.fg, bold = true })
	vim.api.nvim_set_hl(0, "@markup.italic", { fg = colours.fg, italic = true })
	vim.api.nvim_set_hl(0, "@markup.link", { fg = colours.blue })
	vim.api.nvim_set_hl(0, "@markup.list", { fg = colours.mauve })
	vim.api.nvim_set_hl(0, "@markup.code", { fg = colours.green })
	vim.api.nvim_set_hl(0, "@markup.quote", { fg = colours.subtext })
	vim.api.nvim_set_hl(0, "Conditional", { fg = colours.mauve })
	vim.api.nvim_set_hl(0, "Repeat", { fg = colours.mauve })
	vim.api.nvim_set_hl(0, "Function", { fg = colours.sapphire })
	vim.api.nvim_set_hl(0, "Bold", { fg = colours.fg, bold = true })
	-- Markdown headings
	vim.api.nvim_set_hl(0, "@markup.heading.1", { fg = colours.mauve, bold = true })
	vim.api.nvim_set_hl(0, "@markup.heading.2", { fg = colours.peach, bold = true })
	vim.api.nvim_set_hl(0, "@markup.heading.3", { fg = colours.yellow, bold = true })
	vim.api.nvim_set_hl(0, "@markup.heading.4", { fg = colours.green, bold = true })
	vim.api.nvim_set_hl(0, "@markup.heading.5", { fg = colours.red, bold = true })
	vim.api.nvim_set_hl(0, "@markup.heading.6", { fg = colours.subtext, bold = true })
end