return function(colours)
	local highlights = {
		["@variable"] = { fg = colours.sapphire },
		["@Keyword"] = { fg = colours.mauve },
		["@constant"] = { fg = colours.mauve },
		["@lsp.type.enumMember"] = { fg = colours.sapphire },
		["@method.call"] = { fg = colours.blue },
		["@function"] = { fg = colours.sapphire },
		["@function.call"] = { fg = colours.sapphire },
		["@function.macro"] = { fg = colours.mauve },
		["@type"] = { fg = colours.green },
		["@type.builtin"] = { fg = colours.mauve },
		["@parameter"] = { fg = colours.subtext },
		["@attribute"] = { fg = colours.subtext },
		["@property"] = { fg = colours.blue },
		["@boolean"] = { fg = colours.yellow },
		["@operator"] = { fg = colours.blue },
		["@module"] = { fg = colours.yellow },
		["@include"] = { fg = colours.mauve },
		["@label"] = { fg = colours.red },
		["@character"] = { fg = colours.yellow },
		["@float"] = { fg = colours.sapphire },
		["@string.special"] = { fg = colours.red },
		["@punctuation.delimiter"] = { fg = colours.subtext },
		["@punctuation.bracket"] = { fg = colours.subtext },
		["@markup.heading"] = { fg = colours.mauve, bold = true },
		["@markup.strong"] = { fg = colours.fg, bold = true },
		["@markup.italic"] = { fg = colours.fg, italic = true },
		["@markup.link"] = { fg = colours.blue },
		["@markup.list"] = { fg = colours.mauve },
		["@markup.code"] = { fg = colours.green },
		["@markup.quote"] = { fg = colours.subtext },
		Conditional = { fg = colours.mauve },
		Repeat = { fg = colours.mauve },
		Function = { fg = colours.sapphire },
		Bold = { fg = colours.fg, bold = true },
		-- Markdown headings
		["@markup.heading.1"] = { fg = colours.mauve, bold = true },
		["@markup.heading.2"] = { fg = colours.peach, bold = true },
		["@markup.heading.3"] = { fg = colours.yellow, bold = true },
		["@markup.heading.4"] = { fg = colours.green, bold = true },
		["@markup.heading.5"] = { fg = colours.red, bold = true },
		["@markup.heading.6"] = { fg = colours.subtext, bold = true },
	}
	for group, opts in pairs(highlights) do
		vim.api.nvim_set_hl(0, group, opts)
	end
end